### ISSUE TITLE
23rd Dec - 2nd Jan Sprint

### ISSUE THREAD

**Issue by ChakshuGautam** [Unified-Learner-Passbook/docs#1]
1. [ ] Migrate Clients to ReactJS (in decreasing order or priority) Unified-Learner-Passbook/Holder-Wallet#1
	- [ ] Wallet (https://learncard.app/achievements) - make this a defacto wallet for ULP -@Shruti3004 @prtkjakhar 	        
		- [ ] Import Credentials using an external agency Unified-Learner-Passbook/Holder-Wallet#4
			- [ ] Email with a link
			- [ ] QR Code (also, QR Code with shortened URL link)
			- [ ] PDF with a QR Code
		- [ ] Design the features (take help from Learncard) and add a ticket Unified-Learner-Passbook/Holder-Wallet#3
		- [ ] KYC implementation Unified-Learner-Passbook/Holder-Wallet#2
		- [ ] Allow installable wallets (If they are not present, redirect them to the application) Unified-Learner-Passbook/Holder-Wallet#4
		- [ ] Design the email with the installation steps of the wallet  Unified-Learner-Passbook/Holder-Wallet#4
	- [ ] Issuer - Reference Implementation (@Shruti3004 @prtkjakhar) Unified-Learner-Passbook/issuer#1
	- [ ] Verifier - Reference Implementation (@Shruti3004 @prtkjakhar) Unified-Learner-Passbook/Verifier-portal#1
		- [ ] Implementing DID Auth through SDK and notification
2. [ ] Backend Services
	- [ ] Authentication in all MS (FA as an OIDC provider) - @techsavvyash
	- [ ] Authorization MS (OPA Bases) - @ChakshuGautam 
	- [ ] Figure out how to use Actual Aadhaar APIs - @Ansh-Sarkar 
	- [ ] Log Management (Graylog) - @Ansh-Sarkar 
		- [ ] What to log
		- [ ] How to log
		- [ ] How to link logging to Graylog
	- [ ] API Gateway - @ChakshuGautam 
		- [ ] Expose Metrics for this
	- [ ] Mock Aadhar MS Unified-Learner-Passbook/MockAadhar-MS#1
	- [ ] Credential MS @techsavvyash 
		- [ ] Expose the API through Swagger Unified-Learner-Passbook/Credential-MS#1
		- [x] Migrate the database from Postgres to MongoDB Unified-Learner-Passbook/Credential-MS#2
		- [ ] Utility APIs
			- [x] Search by Issuer (Issuer's Application) Unified-Learner-Passbook/Credential-MS#3
			- [x] Search by Holder/Subject (Wallet) Unified-Learner-Passbook/Credential-MS#8
			- [ ] Manage Templates Unified-Learner-Passbook/Credential-MS#9
			- [ ] Render Templates as HTML Pages Unified-Learner-Passbook/Credential-MS#10
			- [ ] Render Templates as PDF Unified-Learner-Passbook/Credential-MS#11
			- [ ] Share Credentials as PDFs, QR codes, ... Unified-Learner-Passbook/Credential-MS#12
		- [ ] Logging Unified-Learner-Passbook/Credential-MS#4
		- [ ] SDK Unified-Learner-Passbook/Credential-MS#5
	- [ ] Credential Schema MS @techsavvyash 
		- [x] Swagger Docs Unified-Learner-Passbook/Cred-Schema-MS#1
		- [x] Test (Postman collection) Unified-Learner-Passbook/Cred-Schema-MS#2
		- [x] Sample Credential Schemas
			- [x] Proof of Training Unified-Learner-Passbook/Cred-Schema-MS#3
			- [x] Proof of Alumni Unified-Learner-Passbook/Cred-Schema-MS#4
			- [x] Poof of Marks Unified-Learner-Passbook/Cred-Schema-MS#5
			- [x] Proof of Passing an Exam Unified-Learner-Passbook/Cred-Schema-MS#6
		- [x] Migrate this to Fastify Unified-Learner-Passbook/Cred-Schema-MS#7
		- [x] Caching implementation (10k request/second) Unified-Learner-Passbook/Cred-Schema-MS#8
		- [ ] SDK Unified-Learner-Passbook/Cred-Schema-MS#9
	- [ ] Notification MS @chinmoy12c 
		- [ ] Manage registration on OIDC Provider
		- [ ] API to allow sending a notification (email, push) to a holder by the issuer through MagicBell (push) and Gmail SMTP Unified-Learner-Passbook/Notification-MS#1 Unified-Learner-Passbook/Notification-MS#2
		- [ ] Move this to UCI later
	- [ ] Identity MS @chinmoy12c 
		- [ ] Bulk Identity Creation API Unified-Learner-Passbook/DID-L3-MS#1
		- [ ] Deferred Identity Creation Unified-Learner-Passbook/DID-L3-MS#2
		- [ ] Retiring Identity Unified-Learner-Passbook/DID-L3-MS#3
		- [ ] Security of Private Keys <Critical> Unified-Learner-Passbook/DID-L3-MS#4
		- [ ] Logging Unified-Learner-Passbook/DID-L3-MS#7
		- [ ] Implement Authorization on all APIs <Most critical>
		- [ ] Scaling Unified-Learner-Passbook/DID-L3-MS#6
			- [ ] Caching implementation for resolution (10k request/second)
		- [ ] Benchmark Resolution of a DID Unified-Learner-Passbook/DID-L3-MS#5
		- [ ] Implementing DID Auth
		- [ ] SDK
	- [ ] Integration Test MS
		- [ ] Steps @techsavvyash 
			- [ ] Create three identities - Issuer, Holder Unified-Learner-Passbook/Integration-Test-MS#1
			- [ ] Issuer issues a credential Unified-Learner-Passbook/Integration-Test-MS#2
			- [ ] Notification is received by the Holder Unified-Learner-Passbook/Integration-Test-MS#3
			- [ ] Holder imported the credential from the notification to the wallet successfully Unified-Learner-Passbook/Integration-Test-MS#4
		- [ ] Jenkins Pipeline @Ansh-Sarkar 
			- [ ] Deploy the test on a server
			- [ ] Run the test
			- [ ] Return output as command line text
			- [ ] Publish this as a GitHub commit
3. [ ] CI/CD
	- [ ] Jenkins Pipeline Unified-Learner-Passbook/ULP-devops#1
		- [ ] MS 
		- [ ] Database pipelines  Unified-Learner-Passbook/ULP-devops#4
		- [ ] Integration Test MS 
		- [ ] Additional services  
			- [ ] Graylog
			- [ ] <Sentry??>
			- [ ] <Posthog??>
			- [ ] FusionAuth
	- [ ] Unit Testing (coverage on the critical path) on GitHub Actions Unified-Learner-Passbook/ULP-devops#3
	- [x] Manual Build and Deploy
	- [x] Swarm base orchestration Unified-Learner-Passbook/ULP-devops#2
	- [ ] Deployment Verification @Ansh-Sarkar 
4. [ ] Benchmarking ([Locust](https://locust.io/)) @Ansh-Sarkar 
	- [ ] APIs at the gateway level 
	- [ ] Role resolution on Authorization MS
5. [ ] Demo
	- [ ] Storyline @ChakshuGautam 
	- [ ] Mockups @Shruti3004 
	- [ ] Video @Ansh-Sarkar - Storyline and Recording (with Audio) - UP Implementation
	- [ ] Video @Ansh-Sarkar - Storyline and Recording (with Audio) - Community
	- [ ] Video @Ansh-Sarkar - Storyline and Recording (with Audio) - Contributors
6. [ ] Documentation
	- [ ] Mocks for entire frontend development - @Shruti3004 @prtkjakhar 
	- [ ] Frontend Tech Stack @Shruti3004 
	- [ ] Backend
		- [ ] Swagger APIs are for Microservices (Auto Generated)
		- [ ] API Gateway => Postman Collection => Postman Documentation
